name = "fridge"
compatibility_date = "2024-01-01"

[assets]
directory = "./dist"

[vars]
VITE_SUPABASE_URL = "https://oiqrwqvuspsepioaoysi.supabase.co"
VITE_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_4EwpY6qi4A9QPmup3mO-Jg_yCH3gRyO"
